export type BlogPostStatus = "draft" | "published"

export type BlogPost = {
  slug: string
  title: string
  summary: string
  authorName: string
  publishedAt: string
  status: BlogPostStatus
  readingTime: string
  eyebrow: string
  body: string
}

const blogPosts: BlogPost[] = [
  {
    slug: "why-rikba-is-launching-in-malta",
    title: "Why Rikba Is Launching in Malta",
    summary:
      "Rikba is launching in Malta with a local-first transport model built around lower rider prices, better driver economics, and keeping more value on the island.",
    authorName: "Rikba Team",
    publishedAt: "2026-04-20",
    status: "published",
    readingTime: "8 min read",
    eyebrow: "Launch",
    body: `Malta does not need another app that simply copies what already exists. It needs a transport platform that understands the island, respects the people using it every day, and builds something that actually makes sense for the local economy.

That is why Rikba is launching in Malta.

Rikba is not being built as a generic ride-hailing product dropped onto the island from somewhere else. It is being designed around the real needs of Malta and Gozo: lower prices for riders, better economics for drivers, and a model that keeps more value circulating locally instead of sending it away.

## Malta deserves a ride platform built for Malta

Transport in Malta is not just about moving from one point to another. It is part of daily life. It affects workers getting to their shifts, students reaching class, families managing their routines, tourists navigating the island, and drivers trying to earn a decent living in a market that has become increasingly squeezed.

Over time, many people have started to feel the same frustration. Riders want reliability, but they also want fairer prices. Drivers want access to demand, but they also want a system where their work is properly rewarded. The island needs innovation, but it also needs loyalty to local realities.

Rikba begins with a simple belief: a mobility platform should not only be efficient. It should also be fair.

## Lower rider prices without stripping quality

For riders, price always matters. But low prices alone are not enough if the experience becomes unreliable, inconsistent, or frustrating. Rikba is being developed with the goal of offering stronger value, not just a temporary discount.

That means building an experience where booking a ride feels simple, transparent, and dependable. It means helping users feel that they are paying a fair price for a service they can trust. It means creating a platform where affordability is not achieved by weakening the people doing the work.

Malta has a fast-moving daily rhythm. People want quick decisions, clear expectations, and less friction. Rikba is being shaped with that in mind. Riders should not feel that every trip is a compromise between price and dignity. The goal is to make everyday transport more accessible while keeping standards high.

## Better economics for drivers

A ride platform cannot succeed long term if the people behind the wheel feel squeezed from every side.

Drivers are not just a supply layer in a system. They are the real service on the ground. They are the face of the trip, the ones dealing with traffic, timing, customer expectations, road pressure, and long working hours. If drivers are not earning fairly, the whole system becomes unstable.

Rikba is being built with stronger driver economics as a core principle, not as an afterthought.

That matters because when drivers are treated better, the quality of the platform improves naturally. A driver who feels respected is more likely to stay, perform well, and take pride in the service. Better driver economics does not only help drivers. It improves consistency for riders and creates a healthier marketplace overall.

Malta needs a platform where drivers can see a real future, not just short-term survival.

## Keeping value on the island

This is one of the most important parts of the Rikba story.

Many digital platforms are efficient at extracting value from local markets. They enter, scale, and move money outward. The island generates the activity, but too much of the value leaves the island.

Rikba is being built with a different mindset.

The vision is not just to operate in Malta. It is to belong to Malta. That means creating a product whose growth has local meaning. It means supporting a model where more of the economic value generated by transport remains closer to the people and businesses actually creating it.

When a platform is rooted in local reality, it starts making different decisions. It pays more attention to what riders actually need. It listens more closely to drivers. It takes the island seriously, not just as a market opportunity, but as a community.

That difference matters.

## Built with local understanding, not distant assumptions

Malta is unique. Its transport patterns, road realities, seasonal changes, tourism pressure, and geographic scale create a mobility environment that cannot be fully understood from afar.

What works in a large mainland city does not always work here. What sounds efficient in a boardroom can feel disconnected on the street. Malta needs solutions shaped by the texture of island life.

Rikba is being built with that local sensitivity in mind. The platform is not meant to feel imported. It is meant to feel relevant. The needs of a rider in Valletta, a worker finishing late in Sliema, a family moving across central Malta, or a passenger navigating Gozo are not abstract use cases. They are the reality the product must serve.

A platform earns trust when users feel that it understands the place they live in.

## Trust, usability, and a better everyday experience

People do not stay with a platform only because of price. They stay because the experience feels right.

That means the app must be clear, fast, and reliable. Booking a ride should feel natural. Information should be easy to understand. The flow should reduce stress, not create it. Drivers should be able to work without unnecessary friction. Riders should feel in control from pickup to drop-off.

Rikba is being shaped around that kind of product thinking. The ambition is not to launch something noisy. It is to launch something solid. A platform that feels modern, trustworthy, and calm. A platform that people can quickly make part of their daily life.

In a crowded digital world, quality often shows up in the details. The details matter because they shape whether people come back.

## A platform with long-term intention

Rikba is not being launched as a short burst of attention. The goal is to build something durable.

That requires patience, discipline, and a willingness to get the fundamentals right. It means creating a foundation strong enough to support riders, drivers, and future growth without losing the original mission.

The transport space in Malta is too important for shallow solutions. This is not just about getting installs. It is about building a service people can rely on, recommend, and believe in.

That kind of trust is earned over time. Rikba is entering the market with the intention to earn it.

## Why now

Malta is at a moment where people are more aware than ever of the trade-offs built into the services they use. They notice pricing. They notice quality. They notice whether a system feels fair. They notice whether value is staying close to home or disappearing elsewhere.

That creates room for a platform with a clearer promise.

Rikba is launching now because the island is ready for an alternative that takes all three sides seriously at once: the rider, the driver, and the local economy.

That combination is not a marketing slogan. It is the point.

## The bigger idea behind Rikba

At its heart, Rikba is about more than booking rides.

It is about building a better balance between convenience and fairness. It is about proving that a transport platform can be modern without becoming detached, competitive without becoming extractive, and ambitious without forgetting where its value comes from.

Malta deserves technology that works for the island, not just on the island.

That is why Rikba is launching in Malta.

Because riders deserve better value.
Because drivers deserve better economics.
Because the island deserves a platform that keeps more of its value where it belongs.

And because sometimes the best ideas are not the ones that arrive the loudest, but the ones built with the clearest purpose.`,
  },
  {
    slug: "how-rikba-thinks-about-safety-and-trust",
    title: "How Rikba Thinks About Safety and Trust",
    summary:
      "Safety, clarity, and platform trust are not side features. They shape how Rikba writes policy, designs flows, and communicates with users.",
    authorName: "Rikba Team",
    publishedAt: "2026-04-18",
    status: "published",
    readingTime: "5 min read",
    eyebrow: "Safety",
    body: `## Safety starts before the trip

Safety on a ride-hailing platform is not limited to the trip itself. It starts with clear onboarding, honest identity details, and product decisions that reduce ambiguity for both riders and drivers.

## Clear public policies matter

When legal pages, contact information, and community guidelines are easy to find, the platform becomes easier to trust. Users should not have to guess how to request support, report an issue, or understand their responsibilities.

## Product trust is operational

- clear terms and privacy information
- accessible contact details
- visible community expectations
- transparent blog updates when the public site changes

## Trust compounds

Good trust systems are cumulative. Each clear policy, reliable support path, and transparent launch update makes the overall service feel more credible.`,
  },
  {
    slug: "summer-launch-checklist",
    title: "Summer Launch Checklist",
    summary:
      "Internal launch planning note for public rollout sequencing.",
    authorName: "Rikba Team",
    publishedAt: "2026-04-22",
    status: "draft",
    readingTime: "3 min read",
    eyebrow: "Draft",
    body: `## Draft only

This post exists to demonstrate publish-state filtering in the static website data source.

## Not public

Draft posts must not appear on the public blog index or slug pages.`,
  },
]

function sortPosts(posts: BlogPost[]) {
  return [...posts].sort((left, right) => right.publishedAt.localeCompare(left.publishedAt))
}

export function getPublishedBlogPosts() {
  return sortPosts(blogPosts.filter((post) => post.status === "published"))
}

export function getPublishedBlogPost(slug: string) {
  return getPublishedBlogPosts().find((post) => post.slug === slug) ?? null
}

export function formatBlogDate(value: string) {
  return new Intl.DateTimeFormat("en-MT", {
    day: "numeric",
    month: "long",
    year: "numeric",
  }).format(new Date(value))
}